apiVersion: apps/v1
kind: Deployment

metadata:
  name: products-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: products

  template:
    metadata:
      labels:
        app: products

    spec:
      containers:
        - name: products

          image: nnirmal24/kubecart-products:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8002

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          env:
            - name: PORT
              value: "8002"

            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGODB_PRODUCTS

            - name: MSG_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MSG_QUEUE_URL

            - name: EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EXCHANGE_NAME

            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_SECRET