apiVersion: apps/v1
kind: Deployment

metadata:
  name: shopping-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: shopping

  template:
    metadata:
      labels:
        app: shopping

    spec:
      containers:
        - name: shopping

          image: nnirmal24/kubecart-shopping:latest

          ports:
            - containerPort: 8003

          env:
            - name: PORT
              value: "8003"

            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGODB_SHOPPING

            - name: MSG_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MSG_QUEUE_URL

            - name: EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EXCHANGE_NAME

            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_SECRET